apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mydemo
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: mbunwevicki100/argocd-demo
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/mbunwevicki100_argocd-demo.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/mbunwe-victor/argocd-demo2
    targetRevision: HEAD
    path: charts/mydemo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
